/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.test3;

public class App {
  public String getGreeting() {
    return "Hello Java!";
  }
  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    for (int i = 0; i < 5; i++) {
      System.out.println(i);

    }
    System.out.println("오늘 날씨가 좋네요!");
  }
}
